local Harness = require("support.wow")
local FakeLibs = require("support.fake_libs")

local function loadUI()
    local LibStub, log = FakeLibs.new()
    local ns = Harness.new({ globals = { LibStub = LibStub } }):load("Core/UI.lua")
    return ns.UI, log.AceGUI
end

describe("UI.Window", function()
    it("builds nothing until shown", function()
        local UI, gui = loadUI()
        local window = UI.Window({ title = "Test", width = 300, height = 200 })
        assert.is_false(window:IsShown())
        assert.are.equal(0, #gui.created)
    end)

    it("builds a titled, sized frame when shown", function()
        local UI, gui = loadUI()
        UI.Window({ title = "Test", width = 300, height = 200 }):Show()
        local frame = gui.created[1]
        assert.are.equal("Test", frame.title)
        assert.are.equal(300, frame.width)
        assert.are.equal(200, frame.height)
    end)

    it("shows only one frame at a time", function()
        local UI, gui = loadUI()
        local window = UI.Window({ title = "Test", width = 300, height = 200 })
        window:Show()
        window:Show()
        assert.are.equal(1, #gui.created)
    end)

    it("releases the frame when hidden", function()
        local UI, gui = loadUI()
        local window = UI.Window({ title = "Test", width = 300, height = 200 })
        window:Show()
        window:Hide()
        assert.is_false(window:IsShown())
        assert.are.equal(gui.created[1], gui.released[1])
    end)

    it("releases the frame when the player closes it", function()
        local UI, gui = loadUI()
        local window = UI.Window({ title = "Test", width = 300, height = 200 })
        window:Show()
        gui.created[1].callbacks.OnClose(gui.created[1])
        assert.is_false(window:IsShown())
        assert.are.equal(1, #gui.released)
    end)

    it("toggles", function()
        local UI = loadUI()
        local window = UI.Window({ title = "Test", width = 300, height = 200 })
        window:Toggle()
        assert.is_true(window:IsShown())
        window:Toggle()
        assert.is_false(window:IsShown())
    end)
end)
